<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <IsPackable>true</IsPackable>
    <PackageId>JevDotNet</PackageId>
    <Title>JevDotNet</Title>
    <Version>0.9.1</Version>
    <Authors>Rasmus Wulff Jensen</Authors>
    <Company>RWJDK</Company>
    <Copyright>2026</Copyright>
    <Description>An opinionated and convention-based .NET implementation of the Jev SystemOne AI by TypeSafeAI</Description>
    <PackageTags>jev;typesafe-ai;classification;ai</PackageTags>
    <PackageProjectUrl>https://github.com/rwjdk/jev-dotnet</PackageProjectUrl>
    <RepositoryUrl>https://github.com/rwjdk/jev-dotnet.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <DebugType>portable</DebugType>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>https://github.com/rwjdk/jev-dotnet/blob/main/CHANGELOG.md</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
